services:
    local:
        container_name: sync-env_local
        build:
            context: .
            args:
                HOST_UID: ${UID:-1000}
                HOST_GID: ${GID:-1000}
        volumes:
            - .:/var/www/app
